# Generated by Django 4.0.6 on 2022-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.CharField(max_length=70, verbose_name='E-mail')),
            ],
        ),
    ]
