# Generated by Django 4.0.6 on 2022-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='E-mail'),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('data', models.DateField(verbose_name='%d/%m/%Y')),
                ('duracao', models.DurationField(verbose_name='%H:%M')),
                ('participante', models.ManyToManyField(to='core.formacao')),
            ],
        ),
    ]
