# Generated by Django 4.0.6 on 2022-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_participante_email_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='participante',
            field=models.ManyToManyField(to='core.participante'),
        ),
    ]
