# Generated by Django 4.0.6 on 2022-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_formacao_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacao',
            old_name='participante',
            new_name='participantes',
        ),
    ]
