# Generated by Django 4.0.6 on 2022-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formacaoparticipantes_alter_formacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='formacoes',
            field=models.ManyToManyField(through='core.FormacaoParticipantes', to='core.formacao'),
        ),
    ]
