# Generated by Django 4.0.6 on 2022-08-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_formacao_formacaoparticipantes_formacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacaoparticipantes',
            old_name='formacoes',
            new_name='formacao',
        ),
    ]
